version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: zarras
      POSTGRES_PASSWORD: zarras
      POSTGRES_DB: database_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
